valid_settings = [
    # "maintenance",
    # "will_be_delisted",
    # "is_delisted",
    # "hascold",
    # "is_node",
    {"confirmations": int},
    # "is_hidden",
    # "is_internal",
    # "has_withdrawal_limit",
    # "solosend",
    # "deposit_enabled",
    # "withdrawal_enabled",
    {"is_basecurrency": bool},
    # "max_tx_amount",
    # "min_input_amount",
    # "send_type",
    # "decimals",
    # "gitrepo",
    # "explorer",
    # "forum",
    # "contact",
    # "wiextra1",
    # "wiextra2",
    # "tx_fee",
    #"wd_fee"
]
