version: "3.3"

services:
  mongo_db:
    image: mongo
    env_file:
      - .env.test
    volumes:
      - mongo-data:/data/db
      - './app/app/tests/.db_data:/dump/'
      - './scripts/create_db_user_test.js:/docker-entrypoint-initdb.d/create_db_user_test.js'
      - './scripts/restore_test_db.sh:/docker-entrypoint-initdb.d/restore_test_db.sh'

    ports:
      - 27017:27017

  backend:
#    image: 'wallet-service:latest'
    depends_on:
      - mongo_db
    env_file:
      - .env.test
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - wallet-data:/root/.bitcoinlib
    ports:
    - 8040:80

volumes:
  mongo-data:
  wallet-data:

