apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmchart.fullname" . }}-eth
  labels:
    helm.sh/chart: helmchart-0.1.0
    app.kubernetes.io/name: wallet-service-eth
    app.kubernetes.io/instance: wallet-eth
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8545
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: wallet-service-eth
    app.kubernetes.io/instance: wallet-eth

