# Default values for helmchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 551678202612.dkr.ecr.us-east-2.amazonaws.com/auth-service
  pullPolicy: Always

imagePullSecrets: []
nameOverride: "auth-service"
fullnameOverride: "auth-service"

environments:
  - name: "API_V1_STR"
    value: "/api/v1/user"
  - name: "PROJECT_NAME"
    value: "auth-service"
  - name: "MONGODB_URL"
    value: "bf-mongo-mongodb-0.bf-mongo-mongodb-headless.dev.svc.cluster.local:27017,bf-mongo-mongodb-1.bf-mongo-mongodb-headless.dev.svc.cluster.local:27017"
  - name: "MONGODB_NAME"
    value: "auth"
  - name: "USE_REPLICA_SET"
    value: "!!string true"
  - name: "ACCESS_TOKEN_EXPIRE_MINUTES"
    value: "!!string 2"
  - name: "REFRESH_TOKEN_EXPIRE_MINUTES"
    value: "!!string 1440"
  - name: "DOMAIN"
    value: "bullflagtest.com"
  - name: "EMAILS_FROM_NAME"
    value: "Bullflagtest.com"
  - name: "EMAILS_FROM_EMAIL"
    value: "noreply@bullflagtest.com"
  - name: "SMTP_HOST"
    value: "email-smtp.us-east-2.amazonaws.com"
  - name: "SMTP_PORT"
    value: "!!string 587"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

deployment:
  livenessProbe:
    path: '/api/v1/user/health'

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_headers "location";

  hosts:
    - host: bullflagtest.com
      paths: ['/api/v1/user', '/api/v1/a/user']
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
