# Default values for helmchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 551678202612.dkr.ecr.us-east-2.amazonaws.com/balance-service
  pullPolicy: Always

imagePullSecrets: []
nameOverride: "balance-service"
fullnameOverride: "balance-service"

environments:
  API_V1_STR:  "/api/v1/balance"
  PROJECT_NAME: "balance-service"
  MONGODB_URL: "bf-mongo-mongodb-0.bf-mongo-mongodb-headless.dev.svc.cluster.local:27017,bf-mongo-mongodb-1.bf-mongo-mongodb-headless.dev.svc.cluster.local:27017"
  MONGODB_NAME: "balance"
  USE_REPLICA_SET: "!!string true"
  AUTH_SERVICE_URL: "https://bullflagtest.com/api/v1/user"
  WALLET_SERVICE_URL: "https://bullflagtest.com/api/v1/currency"
  AUTH_METHOD: "/login/"
  ASSET_CONFIG_PATH: "/app/config/assets.json"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

deployment:
  livenessProbe:
    path: '/api/v1/balance/health'

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_headers "location";

  hosts:
    - host: bullflagtest.com
      paths: ['/api/v1/balance', '/api/mock/balance']
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
